name: Build

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm install
      # gitに日本語ファイル名に対応させる。
      - run: git config --global core.quotepath false
      - run: npm run build-location-data
      - run: npm run build-standard-data
      - run: npm run build-api
      - run: npm run build-data-updates

